version: "3.8"

services:
  db:
    image: postgres:12
    container_name: docker_db

    environment:
      - POSTGRES_DB=${POSTGRESQL_NAME}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}

    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - "5432"

  back:
    build: .
    container_name: docker_uwsgi
    depends_on:
      - db
    command: >
      sh -c "chmod +x ./wait-for-it.sh  && cp -r /usr/local/lib/python3.7/site-packages/drf_yasg/static/drf-yasg/ ./static/ && ./wait-for-it.sh db:5433 && python manage.py makemigrations  && python manage.py migrate  && python create_init.py && uwsgi uwsgi_nginx.ini "
    volumes:
      - .:/home/dailyview/
    expose:
      - "8002"
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: docker_nginx
    ports:
      - "8001:8001"
    volumes:
      - ./static:/home/dailyview/static
    depends_on:
      - back

  cache:
    image: redis
    container_name: docker_redis
    ports:
      - "6380:6379"
