# Generated by Django 3.2 on 2023-08-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoutToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=256, verbose_name='登出token')),
                ('exp_time', models.DateTimeField(verbose_name='原過期時間')),
            ],
            options={
                'db_table': 'LogoutToken',
            },
        ),
    ]
