# Generated by Django 3.2 on 2023-08-26 22:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_logouttoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logouttoken',
            name='exp_time',
        ),
        migrations.AddField(
            model_name='logouttoken',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登出時間'),
            preserve_default=False,
        ),
    ]
